name: Deploy to GitHub Pages

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Inject the Webhook URL into a JavaScript file
      - name: Create config.js with the webhook URL
        run: echo "const WEBHOOK_URL = '${{ secrets.WHU }}';" > config.js

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
